// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuJoTgPJYm-eU7doXHk8Hmi3dYLz08urU',
    appId: '1:213717281968:android:1e8548595cc4f3a6711f75',
    messagingSenderId: '213717281968',
    projectId: 'premium-gift-in-app',
    storageBucket: 'premium-gift-in-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC30pSGpx1oPQc9-9JEQVqI_pq41L4lY7w',
    appId: '1:213717281968:ios:51b41cda28218079711f75',
    messagingSenderId: '213717281968',
    projectId: 'premium-gift-in-app',
    storageBucket: 'premium-gift-in-app.firebasestorage.app',
    androidClientId: '213717281968-mafb62khjvnadnp9qnv34dgpukc3f5gh.apps.googleusercontent.com',
    iosClientId: '213717281968-e2kc413kd78osiv3oedgjjc4236toe7f.apps.googleusercontent.com',
    iosBundleId: 'in.premiumgift.ios',
  );

}